<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'Classification system',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => 'Reserved classification',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Online information',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => 'Online information classification',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Hướng dẫn',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => 'Online help classification',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'GIỚI THIỆU',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '1',
    'show_in_nav' => '1',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'TIN TỨC MỚI',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '2',
    'show_in_nav' => '1',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'BẢO HÀNH',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '3',
    'show_in_nav' => '1',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'BÁO GIÁ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '4',
    'show_in_nav' => '1',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'HỖ TRỢ MUA HÀNG',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '5',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
);
?>