<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'ĐIỆN THOẠI DI ĐỘNG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => 'ĐIỆN THOẠI DI ĐỘNG',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'Pantech Sky Vega',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '8',
    'name' => 'Pantech Sky Vega',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'LG',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '53',
    'name' => 'LG',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'SamSung',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '56',
    'name' => 'SamSung',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Apple iphone',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '55',
    'name' => 'Apple iphone',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'HTC',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '57',
    'name' => 'HTC',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '58',
    'name' => 'Sony',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '59',
    'name' => 'Nokia',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => 'Motorola',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '79',
    'name' => 'Motorola',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => 'MOBILE',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '80',
    'name' => 'MOBILE',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'PHỤ KIỆN IPHONE',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => 'PHỤ KIỆN IPHONE',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '61',
    'name' => 'Tai nghe',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '60',
    'name' => 'Sạc-Cáp',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '22',
    'name' => 'Pin, Dock sạc',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '23',
    'name' => 'Bao da-cover',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '26',
    'name' => 'Ốp lưng - Case',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '63',
    'name' => 'Tấm dán-Miếng dán',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => 'PHỤ KIỆN SAMSUNG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '81',
    'name' => 'PHỤ KIỆN SAMSUNG',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '92',
    'name' => 'Tai nghe',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '89',
    'name' => 'Sạc-Cáp',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '93',
    'name' => 'Pin, Dock sạc',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '88',
    'name' => 'Bao da-cover',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '90',
    'name' => 'Ốp lưng - Case',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => 'Tấm dán-Miếng dán',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'PHỤ KIỆN SKY',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '52',
    'name' => 'PHỤ KIỆN SKY',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => 'Tai nghe',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '94',
    'name' => 'Sạc-Cáp',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 1,
    'id' => '74',
    'name' => 'Pin, Dock sạc',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '96',
    'name' => 'Bao da-cover',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '95',
    'name' => 'Ốp lưng - Case',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => 'Tấm dán-Miếng dán',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => 'PHỤ KIỆN LG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '77',
    'name' => 'PHỤ KIỆN LG',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '78',
    'name' => 'Tai nghe',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => 'Sạc-Cáp',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => 'Pin, Dock sạc',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '84',
    'name' => 'Bao da-cover',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => 'Ốp lưng - Case',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => 'Tấm dán-Miếng dán',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'LINH KIỆN THEO MÁY',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => 'LINH KIỆN THEO MÁY',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Vỏ điện thoại',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => 'Vỏ điện thoại',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'Xương điện thoại',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '67',
    'name' => 'Xương điện thoại',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'Dây nguồn',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '65',
    'name' => 'Dây nguồn',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'Main',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => 'Main',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'Màn Hình, Cảm ứng',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '66',
    'name' => 'Màn Hình, Cảm ứng',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'Cáp cảm biến',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => 'Cáp cảm biến',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'PHỤ KIỆN ĐT KHÁC',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '51',
    'name' => 'PHỤ KIỆN ĐT KHÁC',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => 'Nokia',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'HTC',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => 'HTC',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => 'SONY',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => 'SONY',
  ),
);
?>