<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'ĐIỆN THOẠI DI ĐỘNG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'PHỤ KIỆN IPHONE',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '81',
    'cat_name' => 'PHỤ KIỆN SAMSUNG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'PHỤ KIỆN SKY',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '77',
    'cat_name' => 'PHỤ KIỆN LG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'LINH KIỆN THEO MÁY',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'PHỤ KIỆN ĐT KHÁC',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'Pantech Sky Vega',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  8 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'LG',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  9 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'SamSung',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  10 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Apple iphone',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  11 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'HTC',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  12 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  13 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  14 => 
  array (
    'cat_id' => '79',
    'cat_name' => 'Motorola',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  15 => 
  array (
    'cat_id' => '80',
    'cat_name' => 'MOBILE',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  16 => 
  array (
    'cat_id' => '61',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  17 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  18 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  19 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  20 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  21 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  22 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Vỏ điện thoại',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'Xương điện thoại',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  24 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'Dây nguồn',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'Main',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'Màn Hình, Cảm ứng',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  27 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'Cáp cảm biến',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'HTC',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '72',
    'cat_name' => 'SONY',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '76',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '94',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  33 => 
  array (
    'cat_id' => '74',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '16',
  ),
  34 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  35 => 
  array (
    'cat_id' => '95',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  36 => 
  array (
    'cat_id' => '75',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '78',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '85',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '87',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  41 => 
  array (
    'cat_id' => '86',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '83',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '92',
    'cat_name' => 'Tai nghe',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  44 => 
  array (
    'cat_id' => '89',
    'cat_name' => 'Sạc-Cáp',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  45 => 
  array (
    'cat_id' => '93',
    'cat_name' => 'Pin, Dock sạc',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  46 => 
  array (
    'cat_id' => '88',
    'cat_name' => 'Bao da-cover',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  47 => 
  array (
    'cat_id' => '90',
    'cat_name' => 'Ốp lưng - Case',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  48 => 
  array (
    'cat_id' => '91',
    'cat_name' => 'Tấm dán-Miếng dán',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>